root: true

extends:
  - eslint:recommended
  - prettier
  - plugin:optimize-regex/recommended
  - plugin:regexp/recommended
  - plugin:sonarjs/recommended

plugins:
  - optimize-regex
  - regexp
  - sonarjs
  - no-secrets

rules:
  no-secrets/no-secrets: error

ignorePatterns:
  - dist

overrides:
  - files: ['*.ts', '*.tsx']
    extends: [typescript]

  - files: ['*.js', '*.cjs', '*.mjs']
    excludedFiles: ['src/**/*', 'test/**/*']
    env:
      node: true
      es2021: true
    parserOptions:
      ecmaVersion: latest

  - files: ['*.js', '*.mjs']
    parserOptions:
      sourceType: module

  - files: ['scripts/**/*']
    env:
      node: true
      es2021: true
    parserOptions:
      ecmaVersion: latest
