name: ESLint

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/eslint.yml
      - package.json
      - pnpm-lock.yaml
      - tsconfig*.json
      - '**/.eslint*'
      - '**/eslint.config.*'
      - '**/*.editorconfig'
      - '**/*.[cm]?jsx?'
      - '**/*.tsx?'
      - src/**
      - test/**
  pull_request:
    branches: [main]
    # Same as on push
    paths:
      - .github/workflows/eslint.yml
      - package.json
      - pnpm-lock.yaml
      - tsconfig*.json
      - '**/.eslint*'
      - '**/eslint.config.*'
      - '**/*.editorconfig'
      - '**/*.[cm]?jsx?'
      - '**/*.tsx?'
      - src/**
      - test/**
  workflow_dispatch:

jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    # Don't run for some dependabot PRs.
    # Specifically, stuff that shouldn't affect ESLint outputs.
    # Ex. vitest, husky
    if: |
      !(
        github.event_name == 'pull_request' &&
        github.actor == 'dependabot[bot]' &&
        (
          contains(github.head_ref, 'dependabot/npm_and_yarn/vitest') ||
          contains(github.head_ref, 'dependabot/npm_and_yarn/husky') ||
          contains(github.head_ref, 'dependabot/npm_and_yarn/concurrently') ||
          contains(github.head_ref, 'dependabot/npm_and_yarn/is-ci')
        )
      )
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - name: Run ESLint
        run: npx eslint .
          --format @microsoft/eslint-formatter-sarif
          --output-file eslint-results.sarif
        continue-on-error: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: eslint-results.sarif
          wait-for-processing: true
