# This workflow integrates njsscan with GitHub's Code Scanning feature
# nodejsscan is a static security code scanner that finds insecure code patterns in your Node.js applications

name: njsscan sarif

on:
  push:
    branches: [main]
    # Only run when the actual source code or this workflow has been changed
    paths:
      - .github/workflows/njsscan.yml
      - src/**
      - '**/.njsscan'
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [main]
    # Paths are the same as we use on push
    # This indirectly excludes most dependabot PRs.
    paths:
      - .github/workflows/njsscan.yml
      - src/**
      - '**/.njsscan'
  schedule:
    - cron: '35 5 * * 2' # 05:35 on Tuesdays
  workflow_dispatch:

permissions:
  contents: read

jobs:
  njsscan:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    runs-on: ubuntu-latest
    name: njsscan code scanning
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: nodejsscan scan
        id: njsscan
        uses: ajinabraham/njsscan-action@v7
        with:
          args: 'src --sarif --output results.sarif || true'

      - name: Upload njsscan report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
