name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  vitest:
    name: Test with Vitest
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
          cache-dependency-path: package-lock.json

      - run: npm ci

      - name: Runn Vitest
        run: npm test -- --coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
