name: Tests

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/tests.yml
      - package*.json
      - src/**
      - test/**
      - tsconfig*.json
      - vitest.config.ts
      - wrangler.toml
  pull_request:
    branches: [main]
    # Same paths that are used on push.
    paths:
      - .github/workflows/tests.yml
      - package*.json
      - src/**
      - test/**
      - tsconfig*.json
      - vitest.config.ts
      - wrangler.toml
  workflow_dispatch:

jobs:
  vitest:
    name: Test with Vitest
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    # Don't run for some dependabot PRs.
    # Particularly, things which should not affect test outputs.
    # Ex. @vitest/ui, ESLint-related stuff, husky.
    if: |
      !(
        github.event_name == 'pull_request' &&
        github.actor == 'dependabot[bot]' &&
        (
          contains('dependabot/npm_and_yarn/typescript-eslint', github.head_ref) ||
          contains('dependabot/npm_and_yarn/vitest/ui',         github.head_ref) ||
          contains('dependabot/npm_and_yarn/husky',             github.head_ref) ||
          contains('dependabot/npm_and_yarn/concurrently',      github.head_ref) ||
          contains('dependabot/npm_and_yarn/eslint',            github.head_ref) ||
          contains('dependabot/npm_and_yarn/lint-staged',       github.head_ref) ||
          contains('dependabot/npm_and_yarn/is-ci',             github.head_ref)
        )
      )
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
          cache-dependency-path: package-lock.json

      - run: npm ci

      - name: Run Vitest
        run: npm test -- --coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
